### ISSUE TITLE
Docker无法启动

### ISSUE THREAD

**Issue by tiyee** [anse-app/chatgpt-demo#443]
### How is Anse deployed?

Docker

### Describe the bug

无法启动，报错，通过docker logs可以看到

```shell
sed: bad option in substitution expression
sed: bad option in substitution expression
sed: bad option in substitution expression
```
我的docker-compose.yml如下

```yaml
  anse:
    image: ddiu8081/chatgpt-demo:latest
    container_name: anse
    restart: always
    ports:
      - "3000:3000"
    environment:
      OPENAI_API_KEY: sk-111111111111111111
```

### Participation

- [ ] I am willing to submit a pull request for this issue.
